import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form";
import Navbar from "../components/Navbar";
import Box from "@mui/material/Box";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login to Al Box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="//fdn.fontcdn.ir" />
        <link rel="preconnect" href="//v1.fontapi.ir" />
        <link href="https://v1.fontapi.ir/css/Vazir" rel="stylesheet" />
      </Head>
      <Navbar />

      <Box display="flex">
        <Box>
          <img style={{ marginTop: "90px" }} src="/background.svg" />
        </Box>
        <Box style={{ flex: "100%" }}>
          <Form />
        </Box>
      </Box>
    </div>
  );
};

export default Home;
